const division = {
  division_name: 'heavy weights',
  min_weight: 200,
  max_weight: 300,
};

const event = {
  name: 'world championship',
  location: 'Barcelona',
  date: '2020-11-14T00:00:00.000Z',
};

const fightOne = {
  winner: 'red',
  method: 'fighting',
  details: 'details',
  rounds: 3,
  round_end_time: 'the end',
  fotn: 'true',
  n_rounds: 'three',
  b_kd: 6,
  b_sig_str_attempts: 7,
  b_sig_str_landed: 45,
  b_total_str_attempts: 7,
  b_total_str_landed: 6,
  b_td_attempts: 8,
  b_td_landed: 2,
  b_sub_att: 54,
  b_reversal: 6,
  b_ctrl: 6,
  r_kd: 7,
  r_sig_str_attempts: 6,
  r_sig_str_landed: 8,
  r_total_str_attempts: 8,
  r_total_str_landed: 8,
  r_td_attempts: 2,
  r_td_landed: 5,
  r_sub_att: 4,
  r_reversal: 3,
  r_ctrl: 3,
  b_kd_r1: 4,
  b_sig_str_attempts_r1: 5,
  b_sig_str_landed_r1: 6,
  b_total_str_attempts_r1: 4,
  b_total_str_landed_r1: 2,
  b_td_attempts_r1: 7,
  b_td_landed_r1: 6,
  b_sub_att_r1: 4,
  b_reversal_r1: 5,
  b_ctrl_r1: 'ring',
  r_kd_r1: 2,
  r_sig_str_attempts_r1: 3,
  r_sig_str_landed_r1: 3,
  r_total_str_attempts_r1: 4,
  r_total_str_landed_r1: 4,
  r_td_attempts_r1: 5,
  r_td_landed_r1: 4,
  r_sub_att_r1: 3,
  r_reversal_r1: 3,
  r_ctrl_r1: 'banana',
};

const fightTwo = {
  winner: 'blue',
  method: 'screaming',
  details: 'details',
  rounds: 5,
  round_end_time: 'the end',
  fotn: 'true',
  n_rounds: 'three',
  b_kd: 6,
  b_sig_str_attempts: 7,
  b_sig_str_landed: 45,
  b_total_str_attempts: 7,
  b_total_str_landed: 6,
  b_td_attempts: 8,
  b_td_landed: 2,
  b_sub_att: 54,
  b_reversal: 6,
  b_ctrl: 6,
  r_kd: 7,
  r_sig_str_attempts: 6,
  r_sig_str_landed: 8,
  r_total_str_attempts: 8,
  r_total_str_landed: 8,
  r_td_attempts: 2,
  r_td_landed: 5,
  r_sub_att: 4,
  r_reversal: 3,
  r_ctrl: 3,
  b_kd_r1: 4,
  b_sig_str_attempts_r1: 5,
  b_sig_str_landed_r1: 6,
  b_total_str_attempts_r1: 4,
  b_total_str_landed_r1: 2,
  b_td_attempts_r1: 7,
  b_td_landed_r1: 6,
  b_sub_att_r1: 4,
  b_reversal_r1: 5,
  b_ctrl_r1: 'ring',
  r_kd_r1: 2,
  r_sig_str_attempts_r1: 3,
  r_sig_str_landed_r1: 3,
  r_total_str_attempts_r1: 4,
  r_total_str_landed_r1: 4,
  r_td_attempts_r1: 5,
  r_td_landed_r1: 4,
  r_sub_att_r1: 3,
  r_reversal_r1: 3,
  r_ctrl_r1: 'banana',
};

const fighterFightsOne = {
  color: 'red',
  fightId: 1,
  fighterId: 1,
};

const fighterFightsTwo = {
  color: 'blue',
  fightId: 1,
  fighterId: 2,
};

const fighterOne = {
  name: 'Rafal',
  nickname: 'Banana',
  height: 'highest',
  weight_lbs: 'lightest',
  reach: 'infinite',
  stance: 'liberal',
  dob: 'spring 2000',
  wins: 'always',
  losses: 'never',
  no_contest: 'apple',
  record: 'great',
  is_champ: true,
  slpm: '5.86',
  str_acc: '100%',
  sapm: '5.22',
  str_def: '39%',
  td_avg: '3.56',
  td_def: '22%',
  td_acc: '48%',
  sub_avg: '8.88',
};

const fighterTwo = {
  name: 'Mandy',
  nickname: 'Destroyer',
  height: 'tall',
  weight_lbs: 'sumo',
  reach: 'far',
  stance: 'wide',
  dob: 'yesterday',
  wins: 'more always',
  losses: 'zero',
  no_contest: 'pineapple',
  record: 'amazing',
  is_champ: false,
  slpm: '5.86',
  str_acc: '100%',
  sapm: '5.22',
  str_def: '39%',
  td_avg: '3.56',
  td_def: '22%',
  td_acc: '48%',
  sub_avg: '8.88',
};

module.exports = {
  division, event, fighterOne, fighterTwo, fighterFightsOne, fighterFightsTwo, fightOne, fightTwo,
};
