name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # The hostname used to communicate with the PostgreSQL service container
      DB_HOST: localhost
      # The default PostgreSQL port
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME_TEST: MMAPI_TEST
      NODE_ENV: test
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        ports:
          - 5432:5432
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wename_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --prefix server
      - name: Connect to PostgreSQL
        run: node ./server/express/models/index.js
      - name: Run Tests
        run: npm test --prefix server