name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:


    - name: Check out code 
      uses: actions/checkout@v2      
    - name: Install dependencies
      run: npm ci
      working-directory: ./server

    - name: Connect to PostgreSQL
        # Runs a script that creates a PostgreSQL client, populates
        # the client with data, and retrieves data
      run: node ./server/express/models/index.js
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
    - name: Run Tests
      run: npm test       
      working-directory: ./server
